- cove/input/templates/datainput/input.html
- cove/static/dataexplore/css/style.css
- cove/templates/explore.html
We load the page with everything extended. We then collapse boxes 2 and 3 if javascript is present.
The boxes act like the bootstrap example now.
Also makes minor changes to explore.html to align style with other pages
Also makes the full bars clickable to expand/collapse
> Makes the accordion work correctly

- cove/templates/explore.html
- cove/tests.py
- cove/views.py
I'm not sure if any of this is how you would want it, so please review carefully!
Alters the view to create a list of unique ocids found in the
releases.
Fixes up tests, and alters the template
> [#30] Adds a list of unique ocids to the explore page

- cove/templates/base_generic.html
- cove/templates/terms.html
- fts/tests.py
We are now Open Data Services Co-operative Limited in our terms
and Open Data Services eleswhere.
Tests are updated to reflect this
Tests common to both index pages are moved into their own test.
> Updates the application with our updated company name

- cove/settings.py
- cove/templates/base_360.html
- cove/templates/multi_index.html
- fts/tests.py
We have been saying 360 Giving with a space.
This removes it and adds tests to make sure 360 Giving is not found
> 360Giving is always 360Giving

- cove/settings.py
- cove/templates/base_360.html
- fts/tests.py
- locale/es/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
- locale/ro/LC_MESSAGES/django.po
Also alters the main site page title to CoVE
Adds tests to check links go to appropriate URL
Checks footer link to see that they actually click through to the
correct sites and see appropriate text. These might not be all that clever
in the longer term, but should flag significant changes perhaps.
Re-runs translastions as some text has been altered
> [#82][#83] Fixes up links from cove to the new 360 site

- cove/input/views.py
- fts/tests.py
If source_url is in the GET params then use GET params instead of POST params to pass to django forms.
CSRF check do not happen on GET requests, so there is no major complication here.
Repeat all functional tests where source_url entered in the form and pass them as GET params as well.
> [#45] Allow source_url as get param

- fts/tests.py
This ensures that the functional tests run sucessfully against the dev site with:
CUSTOM_SERVER_URL=http://dev.cove.opendataservices.coop py.test fts
> [#81] Replace UUID in missing dataset test with a UUID that isn't on dev

- cove/templates/explore.html
- cove/views.py
- fts/tests.py
Add table within a panel that shows frequency and location of first 3 validation errors for each error message.
Refactor functional tests slighlty so that you can provide a list of strings to be found in page instead of needing for the whole test to be run again for different string.
> [#46] Add validation error table.

- fts/tests.py
By checking the server_url in the banner test we should get the
correct behaviour?
> [#81] Should fix tests against appropriate banner for  live or dev

- cove/fixtures/WellcomeTrust-grants_fixed_2_grants.json
- cove/templates/explore.html
- cove/templates/explore_360.html
- cove/templates/explore_ocds-record.html
- cove/templates/explore_ocds-release.html
- cove/templates/modal_list.html
- cove/templatetags/cove_tags.py
- cove/views.py
- fts/tests.py
Add key field information. This includes.
* slight refactoring of explore templates giving the standard specific templates more of the page
* Add modals for lists so that long lists can be displayed
* Change fixtures so that show more errors
* Add more grant aggregates
> [#174] Add 360 key metric information

- cove/static/dataexplore/css/style.css
- cove/templates/base_generic.html
- cove/templates/explore.html
- fts/tests.py
- locale/es/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
- locale/ro/LC_MESSAGES/django.po
Should display on all explore pages, and test has been written for this
Slightly repositioned the language drop down to align with button
Regenerated .po files as text in button can be translated
> [#92] Adds a load new data button

- requirements.txt
- requirements_dev.txt
> [#211] Update requirements and tell requires.io we don't want Django 1.9

- cove/settings.py
This is just to make sure that the first character is not a $.  If it is
then it causes django environ to go into an infinitly recurse.  
See
https://github.com/joke2k/django-environ/issues/60
> [#218] Remove $ from list of random chars.

- cove/input/migrations/0005_auto_20160104_1208.py
- cove/input/models.py
Allows long urls in database and field.
Removes query params from filenames.
Truncates filenames to 100 characters so they can be saved on disk.
> [#195] Allow long urls

- cove/settings.py
- fts/tests.py
Allow you to add enironment variables PREFIX_360 and PREFIX_OCDS to test
endpoints that are not in the normal locations.
There is a also a slight change to config so that if you do not put in
any SENTRY config then it does not use it.
> [#228] Test alternative endpoints

- cove/templates/base_generic.html
using revision.tag seems to work. It will use revision number if there is not a tag.   I have no idea where version came from.
> [#250] Add missing revision

- cove/templates/base_ocds.html
- fts/tests.py
- locale/en/LC_MESSAGES/django.po
- locale/es/LC_MESSAGES/django.po
Fixes a typo in the header of the OCDS validator site.
After merge:
> Post Feb 2016 bug fixes (2) - OCDS validator header typo - live deployment 

- cove/settings.py
Update the ocds schema uri to 1__0__1.
After merge:
> Post Feb 2016 bug fixes (3) - OCDS 1.0.1 - live deployment

- cove/fixtures/badfile.json
- cove/templates/explore_ocds-release.html
- cove/tests.py
- cove/views.py
- fts/tests.py
Catch all main errors caused when decending json objects and do not
show stats if this is the case.  Give warning to user saying this.
Errors will still be raised if the data passes validation but
there is an error in the stats code. So basically we do a good attempt
at producing stats for invalid data but only if the data is close
to being valid.
> [#296] Catch stats producing errors.

- cove/templates/base_ocds.html
- fts/tests.py
On the OCDS 'welcome' page there are many opportunities to link to the
standard, schema etc. This makes those links.
Also adds tests for those links and refactors existing tests to deal
with conflicts where the tests pick the first instance of multiple links
> [#235] Turns text into useful OCDS links

- cove/fixtures/SOURCES
- cove/fixtures/ocds_release_nulls.json
- cove/templates/explore_ocds-release.html
- cove/tests.py
- fts/tests.py
Modify a template to fix a 500 error due to null `tag` field. https://github.com/OpenDataServices/cove/issues/328
Planned deployment date: Tuesday 19th April
After merge:
> Post March 2016 fixes (1) - fix null tag 500 error - live deployment 

- cove/static/dataexplore/css/style.css
- cove/templates/error.html
- fts/tests.py
This button was missing padding and so sitting on top of the div
below
> [#363] Adds some padding to the button

- cove/templates/explore_360.html
- fts/tests.py
For the 360 Key Facts we can hard code this into the template
The link out goes to documetation rather than the schema directly.
I tried to do a test, but it fails. The failure has implications elesewhere
I think so would be good if others could look
> Hard codes the schema link into the Key facts results

- cove/static/dataexplore/css/style.css
- cove/templates/base_generic.html
- cove/templates/explore.html
- cove/templates/explore_360.html
- fts/tests.py
Moves Key Facts to Headlines and to the top of the page
Turns Convert into a half size box at the top
Customises the messages a bit and adds glyphicons
Pluralises grant(s) properly
Hopefully does this without messing up OCDS
> [#380] Layout changes to make the workflow better

- cove/static/dataexplore/css/style.css
- cove/templates/base_360.html
- cove/templates/base_generic.html
- fts/tests.py
Puts the strapline in a block. I don't think will effect OCDS
Updates the tests
> Adds the logo, and moves the site title around

- cove/templates/base_360.html
- cove/templates/common_errors_360.html
- cove/views.py
- fts/tests.py
Also adds a link to the common errors page in the footer [#391]
Wires up views.py to show the new errors
Adds a test to check that the anchors are there on the page
> [#367] Adds the rest of the error messages to the common errors page

- cove/settings.py
And, add an environment variable to turn it on explicitly.
> [#408] Disable django debug toolbar by default

- cove/fixtures/WellcomeTrust-grants_broken_grants.json
- cove/lib/threesixtygiving.py
- cove/static/dataexplore/css/style.css
- cove/templates/explore_360.html
- fts/tests.py
This started off as trying to see why funding org prefixes were not
picked up as failing, and ended up being a copy and paste job of the
receiver org prefixes work.
See if it is useful.
> [#404] Reports on funding org prefixes

- cove/templates/error.html
- cove/views.py
I wanted to make one of the error messages look nicer- specifically when
tender_releases_2_releases_not_json.json was loaded
To do this I think the error message in views.py needs to contain html
I've added the | safe option to the html template
You may not think this is a good idea! Please review.
> Allows html in error messages

- cove/lib/common.py
The code did not take into account where there is a sub object
with a required field, assumed only it would be a list of objects.
Due to this path items where ints and was assuemed to be stings causing
the error.  The code takes this into account now.
Also deletes useless print statement.
> [#469] Fix error on required field

- requirements.txt
- requirements_dev.in
- requirements_dev.txt
This PR updates most requirements to their latest versions https://requires.io/github/OpenDataServices/cove/requirements/?branch=490-update-requirements
Not the latest version are:
* `openpyxl` because flatten-tool doesn't support the latest version https://github.com/OpenDataServices/flatten-tool/issues/135
* `PyFlakes`, because flake8 requests <1.4.0 https://github.com/PyCQA/flake8/blob/master/setup.py
* `CommonMark` because recommonmark requires particular version
* `selenium` because this doesn't work with the version of firefox on travis - https://travis-ci.org/OpenDataServices/cove/builds/190265676 - going forward we probably want to switch to PhantomJS https://github.com/OpenDataServices/cove/issues/518
> Update Python requirements

- cove/fixtures/tenders_releases_2_releases_codelists.json
- cove/lib/common.py
- cove/settings.py
- cove/templates/additional_codelist_values.html
- cove/templates/explore_ocds_base.html
- cove/tests.py
- cove/views.py
- fts/tests.py
Looks up codelists from github and caches them.
Adds two new boxes to frontend one for closed and one for open
codelists.
Removes validation results for enums that also have codelists. This was
a bit messy as it was hard to get out correct properties from jsonschema
when dealing with arrays of enums.
> [#528] codelist verification.

- cove/settings.py
This makes sure there's no output to the expire_files command, which
would laed to uncesseary cron notifications.
> [#762] Only include raven in installed apps if SENTRY_DSN is set

- cove_ocds/templates/cove_ocds/base.html
the relative link was breaking on the "Sorry we can't process that data" page ([example](http://standard.open-contracting.org/validator/data/af449fbb-f88c-49d9-84c7-abcdb40cefe5))
> make sample data link absolute

- cove_ocds/templates/terms_ocds.html
- cove_ocds/urls.py
For avoidance of confusion (mostly my own!) over template overriding, and to avoid accidental changes via overriding, I've copied the Ts&Cs into their own file and modified just for OCDS. We may want to apply the same change to 360, but I'm keen to get this rolled out for OCDS so that I can look at uploads for a week after the change is applied.
> Add OCDS-specific Ts&Cs

- cove/lib/common.py
This is currently making some oneOf errors cause 500 errors: https://sentry.io/open-data-services/cove/issues/456975633/
> json dumps needs to handle decimals

- cove_ocds/tests.py
> Get rid of intermittently failing assertion in OCDS schema cache test

- requirements.txt
- requirements_dev.txt
#940 
Only change to behaviour is to remove duplicate None warnings during Spreadsheet conversion
https://github.com/OpenDataServices/flatten-tool/pull/199
This will affect all instances of CoVE.
> [#940] Update flatten-tool

- cove/templates/terms.html
This is a duplicate of
https://github.com/OpenDataServices/cove/commit/4c075c3d440d08792796616bdc28ec35b48a569a#diff-e793cd92ba35eaa07fd8126406fd764c
This got removed from the OCDS T&Cs by accident during GDPR updates.
This commit also adds it to the T&Cs for 360Giving and IATI CoVEs.
> Add T&Cs for review of submitted data to assess website operation

- cove_ocds/templates/cove_ocds/explore_base.html
Refs #846. It would probably be preferable to use `panel-default`, but I’ve done it this way to make the PR a bit simpler.
> Use `panel-primary` as the default panel class (OCDS)

- cove/lib/common.py
- cove/templates/additional_codelist_values.html
- cove_ocds/fixtures/badfile_all_validation_errors_results.json
- cove_ocds/lib/schema.py
- cove_ocds/templates/cove_ocds/explore_base.html
- cove_ocds/tests.py
User interface updates to make it more obvious when extended/modified codelists have been used for validation. Fixes #1029.
> Linking to extended codelists

- cove/lib/converters.py
This is already enabled for OCDS in it's library - at https://github.com/open-contracting/lib-cove-ocds/commit/3c33bd05c3495cdc5cb4de4cba446d628e1a3674
See https://opendataservices.plan.io/issues/16915
> Enable Flatten-Tool option remove_empty_schema_columns for 360 and IATI.

- setup.py
Though tbh I'm not sure why `cove_360`, `cove_ocds` and `cove_iati` aren't listed here, but they never were, so..
> These packages are no longer in cove (fixes #1102)

- cove_360/lib/threesixtygiving.py
It looks like that mark_safe needs to be in both places, inside `check_text` and in `AdditionalTest` to work everywhere where is used. In this PR I have added it back where it is setup for AdditionalTest
> Add back mark_safe in headings when added in AdditionalTest

- cove_iati/templates/cove_iati/explore.html
Copy of https://github.com/OpenDataServices/cove/pull/1125 so that our tests with secret data run.
> This tweaks the copy to avoid the suggestion that non-embedded codelist
values are checked, too.
>
> Fixes #1124.
> Only embedded codelists are checked

- requirements.txt
- requirements_dev.txt
Fixes issues with hyperlinks in merged cells.
https://bitbucket.org/openpyxl/openpyxl/pull-requests/327/attributeerror-mergedcell-object-attribute/diff
> Update openpyxl to 2.6.2

- cove_360/tests_functional.py
- cove_ocds/fixtures/badfile_all_validation_errors_results.json
- requirements.in
- requirements.txt
- requirements_dev.txt
#1220 
See https://github.com/OpenDataServices/lib-cove/pull/35 for more info — changes to non-test code are all in that PR.
> Improve non unique elements errors

- cove_ocds/templates/cove_ocds/explore_release.html
Adds a space to the template. Transifex did not need to be invoked because the missing space was added outside of a msg string!
> Fix typo, fixes #1092

- cove_ocds/fixtures/badfile_all_validation_errors_results.json
- requirements.in
- requirements.txt
- requirements_dev.txt
> [#1246] Upgrade libcove to 0.12.2

- cove_360/lib/threesixtygiving.py
Use a simple regex to check that the company number is in a valid
format.
Fixes issue https://github.com/OpenDataServices/cove/issues/1291
> 360 cove: Update check_company_number to allow for all types

- cove_360/templates/cove_360/explore.html
'The file was issued on' should not be displayed if the cell in metadata tab is blank.
relates to https://github.com/OpenDataServices/cove/issues/1290
> cove360: templates: explore.html: display metadata 'issued on'

- cove_360/views.py
Metadata keys were uppercase and not being displayed.
Relates to #1290
> cove360: views: explore: metadata: lowercase dict keys.
