OpenDataServices/cove

README.rst, cove/templates/base.html, cove/templates/explore.html, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po
Fixes up the missing translations reported here:
https://github.com/OpenDataServices/cove/issues/4
Also updates the README with instructions to check locally for untranslated stuff
Also regenerates the .po files.
Might want to check the translations in explore.html are done the right way
=> [#4] Translation

cove/static/dataexplore/css/style.css, cove/templates/base.html, fts/tests.py, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ro/LC_MESSAGES/django.po
Footer text added
Name of application changed
.po files hand edited to remove application name translations
=> Adds footer text and changes application name

cove/input/templates/datainput/input.html, fts/tests.py
=> Attempt at a selenium test for submitting an URL

README.rst
Uses an adaptation of Tim's text from the issue
=> [#3] Updates README with info about the application

cove/templates/explore.html, cove/tests.py, cove/views.py, fts/tests.py, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ro/LC_MESSAGES/django.po
Just playing around with picking out some fields that give enough info
to decide whether or not to click through on an OCDS release.
This may or may not be something we want.
=> Adds a simple table to give more info about releases

cove/templates/base_360.html, cove/templates/base_generic.html, cove/templates/base_ocds.html, cove/templates/error.html, cove/templates/explore.html, cove/templates/terms.html, cove/urls.py, cove/views.py, fts/tests.py, locale/es/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/ro/LC_MESSAGES/django.po
A few commits on here to look over Ben
=> Daves working branch

cove/templates/explore.html, cove/views.py
Just some basic stuff based on the basic stuff for ocds
Could do with working out how to handle dates as dates and not
simply as strings
=> [#59] Adds a table and unique id count to the 360 explore page

cove/templates/explore.html, cove/tests.py, cove/views.py
Also tidies up some if statements that were not well defined
=> Refactors code to pass JSON directly to the template

cove/fixtures/SOURCES
This is the paul-hamlyn-foundation-grants_dc.txt file
=> [#71] Updates the SOURCES file with info about a test csv file

cove/dataload/templates/dataload.html, cove/dataload/templates/dataset.html, cove/settings.py, fts/tests.py
Enables the in built django humanize filters
Adds non-comprehensive tests. It should at least catch some of the
work, but checking for all options is a little difficult
=> [#101] Adds the naturaltime filter to the ETL views

cove/templates/explore.html, cove/tests.py, cove/views.py
Contains tests on the view, but no selenium tests.
Considered using FileField for this to turn into a django file
objetc, but considered it not a good enough fit in the end
=> [#42] Display size of files uploaded and converted

cove/views.py, fts/tests.py
=> Original file link missing in explore view.

fts/tests.py
New checks to see firstly if the href attribute has the correct file names in. Secondly to actually request the files to see if they return a 200 and have some size.
=> [#127] Check files actually exist.

cove/settings.py
[#33] SECRET_KEY to be passed by environment variable.
Generate a secret key each time if there is not one supplied and warn user of this.
=> [#33] No public SECRET_KEY

requirements.txt, requirements_dev.txt
Completely straightforward upversion, just like requires.io told us. This was completely painless -- there's got to be some snag?
=> [#142] Update Python requirements

requirements.txt
In response to security fix release
https://www.djangoproject.com/weblog/2015/nov/24/security-releases-issued/
:-)
=> [#151] Updates Django to 1.8.7

cove/settings.py
Enables validation of 360 files.
=> [#68] Add schema package URL for 360

cove/static/dataexplore/css/style.css, cove/templates/explore.html, cove/views.py
This adds zero clipboard with a little icon to copy the text.
=> [#39] Add box to share url.

cove/views.py
Replace uniqueItems validator with one that checks for unique ids.
Remove patternProperties validator.
=> [#155] Validation speedups.

cove/input/templates/datainput/input.html
=> [#157] Add spinner

requirements.txt
This should fix the problems with that XLSX file that was taking forever
to read.
=> [#176] Update flattentool and openpyxl

cove/input/templates/datainput/input.html
On page unload return page to normal
=> [#198] fix spinner on back

cove/templates/base_generic.html, cove/templates/explore.html, cove/templates/explore_360.html, fts/tests.py
The data tables plugin works out of the box and gracefully degrades with no js.
=> [#189] Add data tables for grants.

cove/views.py, fts/tests.py
Check if flattened/unflattened file exists and if they do no rerun flattentool.
Save validation results to disk.
=> [#192] No flattentool and validation on reload

cove/templates/explore.html, cove/templates/explore_360.html
All my mistakes. I am not sure how the tds got in there.
=> [#203] fix tags

cove/templates/explore.html, cove/tests.py, cove/views.py, fts/tests.py
=> [#118] fields in file vs schema

cove/views.py
Make sure we only use values of the correct type.
=> [#193] Check types for grant aggregates.

cove/fixtures/WellcomeTrust-grants_fixed_2_grants.json, cove/fixtures/tenders_releases_2_releases.json, cove/tests.py, cove/views.py, fts/tests.py, requirements.txt
Add format checking. Modify fixtures to pass or fail validation.
For 360 use custom format so it will will accept data-time or dates.
=> [#194] Add format checking

cove/templates/base_generic.html, cove/templates/explore.html, cove/templates/explore_360.html
=> [#203] fix all w3c errors

cove/settings.py, cove/urls_multi.py
For example:
PREFIX_MAP=ocds=validator/,360=360/
will change ocds to be at validator and keep 360 the same.
PREFIX_MAP=ocds=validator/
will remove 360 routes entirely.
=> [#226] Config to allow change of prefix.

cove/views.py
Latin1 has 5 control characters that are not allowed in cp1252.
=> [#220] Decode in latin1 as last resort

cove/static/dataexplore/css/style.css, cove/templates/explore.html
Add collapsables to tables.
Make all a tags a pointer on hover.
Make list of paths a real html list not a comma seperated one.
=> [#215] Few Validation Table Cleanups

cove/templates/explore.html
Make sure data table does not load on very large tables >10000 as it becomes
unusably slow.
Add a show all option.
=> [#221] Limit size of datatable and add show all.

cove/static/dataexplore/css/style.css, cove/templates/explore.html, cove/tests.py, cove/views.py, fts/tests.py
Mostly test fixes to allow for this.
=> [#230] Button to flatten

cove/fixtures/release_aggregate.json, cove/static/dataexplore/css/style.css, cove/templates/explore_ocds-release.html, cove/tests.py, cove/views.py
=> 213 ocds explore

README.rst, cove/templates/base_360.html, cove/templates/base_generic.html, cove/templates/explore.html, cove/templates/explore_ocds-record.html, cove/templates/explore_ocds-release.html, cove/templates/stats.html, cove/templates/terms.html, locale/en/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po
Fix html to work with google translate and add the spanish translation
from transifix.
=> [#238] Spanish machine translate and fixes

cove/templates/base_ocds.html
=> [#84] Add link to CoVE using OCDS sample data

fts/tests.py, requirements.txt
Planned deployment date: 3rd March 2016
After merge:
Specific tasks:
(none)
=> Post Feb 2016 bug fixes (1) live deployment

DEPLOYMENT.md
Currently this is just the checklist to copy/paste into the pull request for deploy.
=> Add a file outlining some steps for our deployment approach

ROADMAP.rst
Would appreciate it if others could sense check this and edit
as appropriate
=> [#277] Adds a simple Roadmap document to the repo

cove/settings.py, cove/views.py, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt, update_requirements.sh
I've also updated the rq.filter hints for sentry, and tweaked some comments and imports to make the new version of flake8 happy.
=> [#285] Update requirements, and add shell script to make update easier

cove/fixtures/tenders_releases_2_releases.json, cove/templates/explore.html, cove/tests.py, cove/views.py, fts/tests.py
Give a warning to ocds users if their is an underscore in any field.
=> [#260] Allow underscores in additional fields

locale/es/LC_MESSAGES/django.po
Updated Spanish translations have been pulled from transifex.
Planned deployment date: 
After merge:
=>  Post March 2016 fixes (1) - update Spanish translations - live deployment

ROADMAP.rst
Following discussions, the roadmap is updated to reflect the work we hope to do in the coming months
=> Updates the Roadmap document with work plans April-July 2016

CONTRIBUTING.md
This is based on a re-write of our generic information that has
not yet been agreed
=> [#149] Adds a contributing document

cove/lib/common.py, cove/lib/converters.py, cove/lib/exceptions.py, cove/lib/ocds.py, cove/lib/threesixtygiving.py, cove/lib/tools.py, cove/tests.py, cove/views.py
=> [#207] Refactor views.py and start to remove Django deps 

cove/templates/common_errors_360.html, cove/templates/explore.html, cove/templates/explore_360.html, fts/tests.py
Also adds a test for this
Also adds anchors css class to anchors on common errors page
=> [#380] Adds an additional fields report to the Headlines

fts/tests.py
Our tests will fail without this fix. (Lets hope they do)
=> [#403] Failing test fix

fts/tests.py
=> [#413] All fts not rerun for checking refresh and param file input

cove/lib/common.py, cove/templates/explore.html, cove/templates/explore_360.html, cove/templates/modal_errors.html, cove/templatetags/cove_tags.py, fts/tests.py
=> [#393] see all validation errors

cove/input/templates/datainput/input.html, cove/templates/explore.html, cove/views.py
This fixes #339, #409, #400
UTC added to timezone
Remove conversion text for CSV, XLSX
Fix javascript so spinner does not appear when form not submitted i.e
when there is an error.
=> [#339] Collection of small fixes

cove/templates/base_generic.html, fts/tests.py
As suggested, as we don't have one, I've removed it
=> [#47] Removes favicon

cove/lib/converters.py, cove/settings.py, cove/tests.py, fts/tests.py, requirements.in, requirements.txt, requirements_dev.txt
Due to the changes in https://github.com/OpenDataServices/flatten-tool/pull/107
This is also the first update to the pinned flatten-tool commit in a while, so will also fix https://github.com/OpenDataServices/cove/issues/377
=> [#422] Update flattentool calls

.travis.yml, README.rst, fts/tests.py, requirements_dev.in, requirements_dev.txt
=> [#347] Add xdist to dev reqs for parallel testing

cove/input/migrations/0006_supplieddata_rendered.py, cove/input/models.py, cove/settings.py, cove/templates/500.html, cove/templates/base_generic.html, cove/templates/error.html, cove/templates/explore.html, cove/views.py
https://github.com/OpenDataServices/cove/issues/11
Also adds a flag to a SuppliedData object so we know whether info about it has been rendered yet.
=> Add some custom piwik dimensions to improve our analytics

cove/settings.py
=> Fix spelling in warning

cove/lib/common.py, cove/lib/converters.py, cove/settings.py, cove/tests.py, cove/views.py
Insead of specifying full url in config just specify the directory where
the files are.  Use extensions to jsonref and jsonschema to generate
uris for refs.
=> [#292] Allow use of alternate schemas.

cove/input/views.py, fts/tests.py
I've added the message to the form label rather than the heading
I think it's neater
I've also added (.json, .csv, .xlsx) to the Upload file label
See what you think
=> [#121] Paste JSON message

cove/templates/explore.html
This effects both 360 and ocds
The Validation Errors and Additional Fields panels are both collapsable
This offering adds expand/collapse icons
Please review to check that the translation strings are well handled
=> Adds collapse/expand icons to collapsable fields

cove/input/models.py, requirements.txt, requirements_dev.txt
=> 330 use content type

cove/lib/common.py, cove/templates/explore.html, fts/tests.py
=> [#402] exclude language field from additional fields by re

cove/templates/base_360.html, cove/templates/base_generic.html
https://github.com/OpenDataServices/cove/issues/440
=> [#440] Remove 360Giving language switcher

cove/input/models.py, cove/input/tests.py, cove/input/views.py
https://github.com/OpenDataServices/cove/issues/162
=> [#162] Error pages for HTTP and Connection errors

cove/input/models.py, cove/input/tests.py, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt
=> 330 content disposition

cove/input/models.py, cove/input/tests.py
=> [#426] Directories not files should be created in media dir

cove/templates/explore.html, fts/tests.py
Changes the text
Updates the tests
=> [#472] Alters conversion errors text to conversion warnings

requirements.txt, requirements_dev.txt
https://docs.djangoproject.com/en/1.8/releases/1.8.16/
=> Update pinned Django version for security updates

cove/lib/common.py, cove/test_hypothesis.py, requirements_dev.in, requirements_dev.txt
Adds some tests of this, and of the explore page more generally using
the hypothesis test library.
#476
=> [#476] Don't 500 error on duplicate IDs with unexpected types

ROADMAP.rst
#443 
@caprenter could you double check this.
=> [#443] Belatedly add the roadmap from August

cove/settings.py
https://github.com/open-contracting/standard/pull/402
=> Update OCDS schema used to 1.0.2

fts/tests.py, requirements.in, requirements.txt, requirements_dev.txt
https://github.com/OpenDataServices/flatten-tool/compare/e098e6518d0db43bf72c0e12232ef4cdfb083546...fc074cd0a4a25b925a05fc0dda0488f17d1c28d5
=> Update pinned flatten-tool commit

.travis.yml, ROADMAP.rst, cove/input/models.py, cove/lib/common.py, cove/settings.py, cove/templates/base_360.html, cove/templates/base_generic.html, cove/templates/terms.html, cove/test_hypothesis.py, cove/tests.py, cove/views.py, fts/tests.py, locale/en/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt
URL for testing: http://release-201611.dev.cove.opendataservices.coop/
Planned deployment date: _1st December 2016_ (pushed back by 1 week)
* Support uppercase file extensions https://github.com/OpenDataServices/cove/issues/482
* Set a custom useragent for cove, that publishers are less likely to block https://github.com/OpenDataServices/cove/issues/346
* Fix some server errors for badly formatted data
- For badly typed IDs https://github.com/OpenDataServices/cove/issues/476
- For a badly formatted records package https://github.com/OpenDataServices/cove/issues/487
* Update the OCDS schema used to 1.0.2 https://github.com/OpenDataServices/cove/pull/498 - I think the only change to validation should be https://github.com/open-contracting/standard/commit/69955454b49c49deb0ab3f77a759ac8bd1149 …
=> End of November 2016 live deployment 

cove/lib/converters.py, cove/templates/explore_360.html, cove/templates/explore_ocds-record.html, cove/templates/explore_ocds-release.html, fts/tests.py
Added additional text to existing Selenium test rather than new test for the info 'no utf-8' message.
=> [#229] Show message for files non utf-8 encoded

cove/lib/common.py, cove/templates/common_errors_360.html, fts/tests.py
Changes the error message and the write up on the common errors page
=> [#523] Provides alternate text for date errors

.travis.yml, cove/lib/ocds.py, fts/tests.py, fts/tests_360.py
I needed this to test the new 360 live deploy #537
=> Fix functional tests so they can run against a live website

requirements.in, requirements.txt, requirements_dev.txt
This includes these flatten-tool pull requests:
https://github.com/OpenDataServices/flatten-tool/pull/139
(Warn about data errors with a custom class)
For this cove issue https://github.com/OpenDataServices/cove/issues/511
https://github.com/OpenDataServices/flatten-tool/pull/140
(Update flatten-tool to work for the OCDS PPP schema)
Fixes this cove issue https://github.com/OpenDataServices/cove/issues/544
=> Update flatten-tool requirement

cove/input/models.py, cove_360/tests.py
#471 
This helps make debugging sentry errors easier.
=> [#471] Add a __repr__ for SuppliedData

cove_360/templates/cove_360/explore.html
=> [#551] cove_360 downloads: show link for xlsx with titles as main download

cove_360/lib/threesixtygiving.py, cove_360/tests.py
=> [#664] 360 additional checks: show locations for multiple funder IDs

.travis.yml, README.rst, cove/locale/en/LC_MESSAGES/django.po, cove/locale/es/LC_MESSAGES/django.po, cove_360/locale/en/LC_MESSAGES/django.po, cove_360/locale/es/LC_MESSAGES/django.po, cove_ocds/locale/en/LC_MESSAGES/django.po, cove_ocds/locale/es/LC_MESSAGES/django.po, docs/deployment.md
Changes to get ready for the next release: https://github.com/OpenDataServices/cove/pull/668
* Merge in the live branch (so that we can pull request against it)
* Update translations
* Update deploy docs
* Update the README
=> Deploy prep

cove_360/templates/cove_360/base.html, cove_360/tests_functional.py
URL for testing: http://release-201705.dev.cove.opendataservices.coop/
Planned deployment date: 
#737 - Fixing broken links to 360 templates
Before merge:
* Re-run translations if any text has changed
* Create a new branch `release-201705` if it doesn't exist.
Steps above need redoing for additional commits.
After merge:
=> Fix broken links to 360 spreadsheet template on live site

cove_iati/settings.py, cove_iati/templates/cove_iati/base.html
=> Remove mention of “IATI Validator”

cove_360/lib/threesixtygiving.py, cove_360/tests.py
=> 568 recommended fields 360 additional checks

cove_ocds/templates/cove_ocds/deprecated_fields_table.html
This is necessary to be able to create a pull request we can merge against the live branch.
=> Merge live branch into master

cove_ocds/settings.py, cove_ocds/tests.py
=> Pull codelists from 1.0 branch not 1.1-dev

cove_360/lib/threesixtygiving.py, cove_360/tests.py
URLs for testing:
* OCDS - http://release-201707.dev.cove.opendataservices.coop/
* 360Giving - http://release-201707.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
Planned deployment: 16th Aug
Fix two 360Giving bugs: #800 #802 
Before merge:
* Re-run translations if any text has changed
* Create a new branch `release-201707` if it doesn't exist.
Steps above need redoing for additional commits.
After merge:
=> Fix 360Giving bugs on live

cove/templates/modal_errors.html, cove_360/lib/threesixtygiving.py, cove_360/templates/cove_360/explore.html, cove_360/tests.py, cove_360/tests_functional.py, cove_iati/templates/cove_iati/explore.html, cove_ocds/templates/cove_ocds/explore_base.html
=> Additional checks 360 'See all' modal

cove/lib/common.py, cove_ocds/fixtures/tender_releases_1_release_with_extension_broken_json_ref.json, cove_ocds/lib/exceptions.py, cove_ocds/lib/schema.py, cove_ocds/tests_functional.py, cove_ocds/views.py
https://github.com/OpenDataServices/cove/issues/809 and also (partially, as it is also a problem with extension dependencies) the cause of a 500 response in https://github.com/OpenDataServices/cove/issues/823
=> Handle jsonref exceptions when resolving refs in SchemaOCDS

requirements.txt, requirements_dev.txt
https://docs.djangoproject.com/en/1.11/releases/1.11.5/#cve-2017-12794-possible-xss-in-traceback-section-of-technical-500-debug-page
=> Update Django due to possible security issue

requirements.in, requirements.txt, requirements_dev.txt
https://github.com/OpenDataServices/flatten-tool/compare/2e51a26354c4dc6179b636596b1cf2b62f194017...3fb433e7f834b2bae3e4a0436df364b37cb48e9b
=> Update flatten-tool commit

cove_iati/iati_schemas/2.02/iati-activities-schema.xsd, cove_iati/iati_schemas/2.02/openag.xsd
=> [#835] Add a openag:tag xsd schema

requirements.txt, requirements_dev.txt, requirements_iati.txt
=> [#859] Update requirements

cove_360/lib/threesixtygiving.py, cove_360/tests.py
=> Delete and comment out two 360 additional checks

cove_iati/lib/iati.py
=> Check whether ruleset errors is a list (CLI) or dict (web)

README.rst
=> [#915] Add mercurial to IATI CoVE installation requirements

cove_360/templates/cove_360/explore.html
=> 360 Additional Checks blurb

cove_360/templates/cove_360/base.html, cove_360/tests_functional.py
=> Cove 360 add sample data upload link

cove_360/templates/cove_360/explore.html
=> Better explanation of Review section usage in Data Summary

cove_ocds/fixtures/release_package_schema_ref_release_schema_deprecated_fields.json, cove_ocds/fixtures/release_schema_deprecated_fields.json
Rather trivial, but it can be useful to explain what those files are doing in fixtures.
=> Add `testing` explanation in "description" of local schema files

README.rst, cove_iati/settings.py, requirements_iati.txt
#915 
This removes the need to install mercurial.
=> Use defusedexpat from GitHub

cove_360/tests_functional.py
=> [#991] Fix tests of links to the 360Giving website

cove_360/lib/threesixtygiving.py, cove_360/templates/cove_360/common_errors.html, cove_360/tests_functional.py
Makes changes to these after work with @KDuerden & @Bjwebb
=> Cove common error text changes

cove_ocds/templates/cove_ocds/explore_record.html
I just changed the column heading, since I think the correct thing is displayed in the table. Hopefully I'm not missing something here (fixes #1012).
=> Records count -> Release count

requirements.txt, requirements_dev.txt
https://docs.djangoproject.com/en/2.1/releases/1.11.15/
=> Django security update

requirements.txt, requirements_dev.txt
https://bitbucket.org/openpyxl/openpyxl/issues/1049
=> Update openpyxl - this fixes the mac epoch issue

cove/lib/converters.py, cove_iati/settings.py
I have manually test it and it works well.
=> Set hash comments default iati

cove_iati/templates/cove_iati/base.html, cove_iati/templates/cove_iati/how_to.html, cove_iati/tests_functional.py
=> Add how to iati cove

cove_ocds/urls.py
URL change was at 76facfe68afe988f5b182bb4b02b36550ded6d5b
=> OCDS - should serve on both URL's, old /validator and new /review

cove_iati/templates/cove_iati/how_to.html
=> Change how to text about upload

cove_360/templates/cove_360/additional_checks.html, cove_360/views.py
I have added the Class Name in the additional checks URL. Is there a changelog in this repository to add this change?
=> Add Class Name in additional checks url

requirements.in, requirements.txt, requirements_dev.txt
https://github.com/OpenDataServices/lib-cove-web/pull/13
https://github.com/OpenDataServices/lib-cove/pull/11
=> Update libcove versions

cove_360/lib/threesixtygiving.py, cove_360/templates/cove_360/explore.html, cove_360/tests.py, cove_360/tests_functional.py
Delete additional checks test class and assign the classes to usefulness or quality_accuracy
=> Additional test classes divide

requirements.in, requirements.txt, requirements_dev.txt
https://github.com/OpenDataServices/flatten-tool/compare/v0.5.0...v0.6.0
Should fix https://github.com/OpenDataServices/cove/issues/977
=> Update flattentool to 0.6.0 and openpyxl to 2.6.2

requirements.in, requirements.txt, requirements_dev.txt
https://github.com/open-contracting/lib-cove-ocds/pull/13
=> Update lib-cove-ocds to the v0.3.0 release

requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt
This libcove update fixes the large blocks of JSON error reporting and oneOf validation message issues.
=> Update libcove, and other requirements

cove_ocds/tests_functional.py
(without this commit, tests fail)
=> Update link test to work with new open contracting website

LICENCE.rst, README.rst, cove_360/tests.py, docs/lib.md
Tidy up from work done in 593df19662943e8540b1510bce015e1af38e333c and d54e3db30c27f0c9906e94877bf7354be5516a76
Correct comment in cove_360/tests.py
=> ocds: Remove references

cove_360/tests_functional.py, cove_iati/lib/exceptions.py, cove_iati/lib/iati.py, requirements.in, requirements.txt, requirements_dev.txt, requirements_iati.txt
flatten-tool PR: https://github.com/OpenDataServices/flatten-tool/pull/339
lib-cove PR: https://github.com/OpenDataServices/lib-cove/pull/49
=>  conversion: Add .ods support 

cove_360/fixtures/fundingproviders-grants-email.json, cove_360/lib/threesixtygiving.py, cove_360/tests.py
relates to https://github.com/OpenDataServices/cove/issues/1298
=> cove360: additional checks: LooksLikeEmail: filter out email fields.

cove_360/templates/cove_360/additional_checks.html
relates to https://github.com/OpenDataServices/cove/issues/1293
=> cove_360: templates: additional_checks.html: Improve formatting.

cove_360/templates/cove_360/base.html, cove_360/tests_functional.py
Link logo image to 360 main webpage.
Relates to https://github.com/OpenDataServices/cove/issues/779
=> cove360: templates: base.html: logo link.
